"use client";

import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import Image from 'next/image';
import { ArrowDown, Check, Code2, Copy, Waves } from 'lucide-react';
import { Action, ContentFrame, Dialog, FAQList, Field, Filter, FormStatus, FramedPhoto, IconControl, LessonIncluded, PageFrame, PhotoGallery, ProcessGrid, ReviewCard, ReviewsSection, Section, SectionHeading, ServiceChoices, Surface, tokenGroups } from '../components/design-system';
import { buildLessonServiceModel } from '../data/lessonServicePage';
import { getSeoPage } from '../data/seoPages';
import { translations } from '../data/translations';
import { googleFeaturedReviews, googleReviewsSummary } from '../data/googleReviews';
import './catalog.css';

const subscribeReady = () => () => {};
const readyClient = () => true;
const readyServer = () => false;
const photoRoot = '/design/home-v5/how-it-works';
const howPhotos = ['meet-photo.webp','theory-photo.webp','practice-photo.webp','review-tips-camera.webp'];
const lessonImages = {
  group: '/design/home-v5/lessons-included/png/group-lesson-photo@2x.png',
  split: '/design/home-v2/lessons/lesson-split-camera.webp', private: '/design/home-v2/lessons/lesson-private-camera.webp',
  surf_skate: '/design/home-v2/lessons/lesson-surf-skate-desktop.webp', lineup_pro: '/design/home-v2/lessons/lesson-line-up-camera.webp',
};
const nav = [ ['foundations','Основы','Foundations'],['actions','Кнопки','Actions'],['surfaces','Карточки и фото','Surfaces & photos'],['compositions','Композиции','Compositions'],['interaction','Формы и FAQ','Forms & FAQ'],['responsive','Адаптивность','Responsive'],['usage','Сборка','Usage'] ];
const snippets = {
  frame: `import { PageFrame, Section, SectionHeading, Action } from '@/app/components/design-system';\n\n<PageFrame locale="ru">\n  <Section>\n    <SectionHeading accent="урок">Выбери свой</SectionHeading>\n    <Action onClick={openBooking}>Записаться</Action>\n  </Section>\n</PageFrame>`,
  action: `<Action onClick={openBooking}>Записаться</Action>\n<Action href="/ru/surfboard-rental-danang" variant="secondary">\n  Выбрать доску\n</Action>\n<Action loading={isSubmitting}>Отправить</Action>`,
  photo: `<FramedPhoto\n  src="/design/home-v5/how-it-works/meet-photo.webp"\n  alt="Инструктор подбирает доску ученику"\n  slot="how-1"\n  ratio="4 / 3"\n/>`,
  process: `<ProcessGrid\n  locale={locale}\n  title={copy.howTitle}\n  accent={copy.howTitleEnd}\n  steps={steps}\n/>\n// step: { id, title, desc, src, alt, slot }`,
  service: `<ServiceChoices\n  locale={locale}\n  items={offers}\n  onChoose={bookFormat}\n  actionLabel={copy.book}\n/>\n// offer: { id, title, price, description, image, contact?, actionLabel? }`,
  review: `<ReviewsSection\n  locale={locale}\n  title={copy.reviews}\n  reviews={verifiedReviews}\n  rating={verifiedRating}\n  href={mapsUrl}\n  transition\n/>`,
  included: `<LessonIncluded\n  title={copy.includedTitle}\n  body={copy.includedIntro}\n  items={includedGroups}\n/>\n// Original EPIC gear artwork is built into this recipe.`,
  gallery: `<PhotoGallery locale={locale} albums={albums} />\n// album: { id, label, photos: [{ src, alt, slot? }] }`,
  form: `<Field label="Имя" name="name" required error={errors.name} />\n<Field as="textarea" label="Комментарий" name="message" />\n<FormStatus kind="error">Проверьте заполнение</FormStatus>\n<Dialog open={open} onClose={close} title="Запись">\n  {form}\n</Dialog>`,
  faq: `<FAQList items={copy.faqItems} />\n// item: { id?, q, a }`,
};
function CodeExample({ code, locale }) {
  const [copied,setCopied]=useState(false);
  const [copyError,setCopyError]=useState(false);
  const timer=useRef(null);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  async function copy() {
    try { await navigator.clipboard.writeText(code);setCopied(true);setCopyError(false);clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),2000); }
    catch { setCopied(false);setCopyError(true); }
  }
  return <details className="ds-code"><summary><Code2 size={17} aria-hidden="true" />{locale==='ru'?'Код использования':'Usage example'}</summary><div><pre tabIndex={0}><code>{code}</code></pre><button type="button" onClick={copy} aria-label={locale==='ru'?'Копировать код':'Copy code'}>{copied?<Check size={17} />:<Copy size={17} />}<span role="status">{copied?(locale==='ru'?'Скопировано':'Copied'):(locale==='ru'?'Копировать':'Copy')}</span></button>{copyError&&<p role="status">{locale==='ru'?'Копирование недоступно. Выделите код вручную.':'Copy is unavailable. Select the code manually.'}</p>}</div></details>;
}
function Spec({ title, description, rule, code, children, locale, className='' }) {
  return <div className={`ds-spec ${className}`}><div className="ds-spec-caption"><h3>{title}</h3><p>{description}</p>{rule&&<small>{rule}</small>}</div><div className="ds-spec-preview">{children}</div>{code&&<CodeExample code={code} locale={locale} />}</div>;
}
function Steps({ locale }) {
  const t=translations[locale];
  return <ProcessGrid locale={locale} title={t.howTitle} accent={t.howTitleEnd} steps={t.howSteps.map((step,index)=>({...step,src:`${photoRoot}/${howPhotos[index]}`,slot:`how-${index+1}`}))} />;
}
function LessonDemo({ locale, onAction }) {
  const model=buildLessonServiceModel(getSeoPage('surf-lessons-danang',locale),locale);
  return <ServiceChoices items={model.sections[0].offers} locale={locale} onChoose={onAction} actionLabel={model.labels.book} />;
}
function IncludedDemo({ locale }) {
  const model=buildLessonServiceModel(getSeoPage('surf-lessons-danang',locale),locale);
  return <LessonIncluded {...model.sections[1]} />;
}
function GalleryDemo({ locale }) {
  return <PhotoGallery locale={locale} albums={[
    {id:'lessons',label:locale==='ru'?'Уроки':'Lessons',photos:howPhotos.map((file,index)=>({src:`${photoRoot}/${file}`,alt:translations[locale].howSteps[index].title,slot:`how-${index+1}`})).concat([{src:lessonImages.group,alt:translations[locale].cards[0].title,slot:'lesson-group'}])},
    {id:'community',label:locale==='ru'?'Комьюнити':'Community',photos:[1,2,3,4,5].map((index)=>({src:`/gallery/umka-party/umka-party-${String(index).padStart(2,'0')}-960.webp`,alt:locale==='ru'?`Праздник Умка, фото ${index}`:`Umka event, photo ${index}`}))},
  ]} />;
}
export function DesignSystemPreview({ locale }) {
  const ready=useSyncExternalStore(subscribeReady,readyClient,readyServer);
  const [open,setOpen]=useState(false),t=translations[locale];
  useEffect(()=>{document.documentElement.lang=locale;},[locale]);
  return <PageFrame locale={locale} className="ds-embed" data-catalog-ready={ready}><Section><Steps locale={locale} /></Section><Section className="ds-textured"><SectionHeading>{locale==='ru'?'Выбери свой формат':'Choose your lesson'}</SectionHeading><div className="ds-demo-spacing"><LessonDemo locale={locale} onAction={()=>setOpen(true)} /></div></Section><ReviewsSection title={locale==='ru'?'Отзывы учеников':'Student reviews'} reviews={googleFeaturedReviews} rating={googleReviewsSummary.rating} href={googleReviewsSummary.referenceUrl} locale={locale} transition /><Section tone="paper"><SectionHeading recipe="utility">FAQ</SectionHeading><div className="ds-demo-spacing"><FAQList items={t.faqItems} /></div></Section><Section><GalleryDemo locale={locale} /></Section><Dialog open={open} onClose={()=>setOpen(false)} title={locale==='ru'?'Пример записи':'Booking example'} closeLabel={locale==='ru'?'Закрыть пример':'Close example'}><p>{locale==='ru'?'Это образец диалога. Реальная запись не отправляется.':'This is a dialog example. No booking is submitted.'}</p><Action onClick={()=>setOpen(false)}>{locale==='ru'?'Готово':'Done'}</Action></Dialog></PageFrame>;
}

export default function DesignSystemCatalog({ initialLocale='ru' }) {
  const ready=useSyncExternalStore(subscribeReady,readyClient,readyServer);
  const [locale,setLocale]=useState(initialLocale),ru=locale==='ru';
  const [dialog,setDialog]=useState(false),[actionState,setActionState]=useState('ready');
  const [email,setEmail]=useState(''),[submitted,setSubmitted]=useState(false),[formState,setFormState]=useState('idle');
  const [previewWidth,setPreviewWidth]=useState('390');
  const [previewActive,setPreviewActive]=useState(false);
  const formTimer=useRef(null);
  const t=translations[locale];
  const tr=(r,e)=>ru?r:e;
  const validEmail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  useEffect(()=>{
    const before=document.documentElement.lang;document.documentElement.lang=locale;
    return ()=>{document.documentElement.lang=before;};
  },[locale]);
  useEffect(()=>()=>clearTimeout(formTimer.current),[]);
  function language(next) { setLocale(next); const url=new URL(location.href);url.searchParams.set('lang',next);history.replaceState(null,'',url); }
  function submit(event) {
    event.preventDefault();setSubmitted(true);
    if(!validEmail){setFormState('error');return;}
    setFormState('loading');clearTimeout(formTimer.current);formTimer.current=setTimeout(()=>setFormState('success'),900);
  }
  return <PageFrame locale={locale} className="ds-catalog" data-catalog-ready={ready}>
    <header className="ds-catalog-header"><ContentFrame><a href="#top" className="ds-catalog-brand" aria-label="EPIC Design System"><Image src="/design/home-v2/hero/epic-logo.svg" alt="EPIC" width={60} height={37} unoptimized /><span>DESIGN SYSTEM <small>02 / 03</small></span></a><div className="ds-catalog-languages" role="group" aria-label={tr('Язык каталога','Catalog language')}><Filter selected={ru} onClick={()=>language('ru')}>RU</Filter><Filter selected={!ru} onClick={()=>language('en')}>EN</Filter></div></ContentFrame></header>
    <main id="top">
      <Section className="ds-catalog-intro"><div className="ds-intro-grid"><div><p className="ds-eyebrow">EPIC SURF SCHOOL · V1 · 05.10.2026</p><SectionHeading as="h1" align="left" accent={tr('система','system')}>{tr('Один стиль.\nПолная','One style.\nOne complete')}</SectionHeading><p className="ds-intro-copy">{tr('Всё, из чего собираются страницы EPIC: цвет, форма, объём, фотографии и живые компоненты. В основе — утверждённая главная.','Everything that builds an EPIC page: color, shape, depth, photography and working components. Built from the approved homepage.')}</p><div className="ds-intro-actions"><Action href="#compositions">{tr('Смотреть композиции','Explore compositions')}</Action><a className="ds-catalog-link" href="#usage">{tr('Как использовать','How to use')} <ArrowDown size={17} aria-hidden="true" /></a></div><p className="ds-intro-meta">{tr('Общие правила → компоненты → секции → страницы','Shared rules → components → sections → pages')}</p></div><div className="ds-intro-photos"><FramedPhoto src={`${photoRoot}/practice-photo.webp`} alt={tr('Практика серфинга с EPIC','Surf practice with EPIC')} slot="how-3" priority ratio="1" /><span className="ds-intro-stamp"><Waves aria-hidden="true" />{tr('СОБРАНО ИЗ ГЛАВНОЙ','BUILT FROM HOME')}</span><FramedPhoto src={`${photoRoot}/review-tips-camera.webp`} alt={tr('Разбор урока с инструктором','Reviewing the lesson with an instructor')} slot="how-4" ratio="1" className="ds-intro-photo-small" /></div></div></Section>
      <nav className="ds-catalog-nav" aria-label={tr('Разделы системы','System sections')}><ContentFrame>{nav.map(([id,r,e])=><a key={id} href={`#${id}`}>{tr(r,e)}</a>)}</ContentFrame></nav>

      <Section id="foundations"><div className="ds-chapter"><span>01 / FOUNDATIONS</span><SectionHeading align="left" accent={tr('характер','character')}>{tr('Узнаваемый','A familiar')}</SectionHeading><p>{tr('Графит, коралл, морские поверхности и настоящие фотографии. Каждый параметр имеет роль и источник.','Graphite, coral, sea surfaces and real photography. Each token has a role and a source.')}</p></div>
        <div className="ds-swatch-grid">{tokenGroups[0].tokens.slice(0,7).map(token=><div className="ds-swatch" key={token.name}><span style={{background:token.value}} /><strong>{token.name.replace('--ds-','')}</strong><code>{token.value}</code></div>)}</div>
        <div className="ds-foundation-grid"><Surface><h3>{tr('Ширина и края','Width and edges')}</h3><p>S = min(94vw, 2160px)<br />C = S × 0.832</p><small>{tr('На desktop от 1200 px. Длинный текст — до 68ch внутри общего каркаса.','Desktop from 1200px. Long text stays within 68ch inside the shared frame.')}</small></Surface><Surface><h3>{tr('Форма и объём','Shape and depth')}</h3><p>{tr('Мягкие карточки, капсулы, верхний блик и нижняя тень.','Soft cards, capsules, a top highlight and a lower shadow.')}</p><small>{tr('Радиус фотографии и радиус карточки — разные роли.','Photo radius and card radius are separate roles.')}</small></Surface><Surface><h3>{tr('Шрифты EN/RU','EN/RU typography')}</h3><p>Recursive · Chivo · Montserrat</p><small>{tr('RU: явный Arial для основного текста, текущий monospace fallback для выразительных заголовков. Montserrat поддерживает кириллицу.','RU: explicit Arial body and the current monospace heading fallback. Montserrat supports Cyrillic.')}</small></Surface></div>
        <Spec locale={locale} title={tr('Типографические роли','Type roles')} description={tr('Выразительный заголовок, спокойный основной текст и утилитарный заголовок не заменяют друг друга.','Expressive headings, ordinary body text and utility headings have separate jobs.')}><div className="ds-type-spec"><div><SectionHeading align="left" accent={tr('на волне','on the wave')}>{tr('Первый раз','First time')}</SectionHeading><p>{tr('Инструктор поможет подобрать доску и объяснит, как уверенно начать. Такой текст должен легко читаться и на телефоне, и на большом экране.','Your instructor will help choose a board and explain how to start with confidence. Body text stays readable on a phone and a large screen.')}</p><small>Recursive / RU fallback · Chivo / Arial</small></div><div><SectionHeading recipe="utility" align="left">{tr('Ответы на вопросы','Your questions answered')}</SectionHeading><p>{tr('Montserrat — подписи и цены. Segoe UI / Arial — вопросы и поля формы.','Montserrat for labels and prices. Segoe UI / Arial for questions and form fields.')}</p><small>Montserrat · Segoe UI / Arial</small></div></div></Spec>
        <details className="ds-token-reference"><summary>{tr('Все токены, значения и источники','All tokens, values and sources')} <span>{tokenGroups.reduce((n,g)=>n+g.tokens.length,0)}</span></summary>{tokenGroups.map(group=><div key={group.id}><h3>{group.label}</h3><div className="ds-table-scroll"><table><thead><tr><th>CSS variable</th><th>{tr('Значение','Value')}</th><th>{tr('Роль / источник','Role / source')}</th></tr></thead><tbody>{group.tokens.map(token=><tr key={token.name}><td><code>{token.name}</code></td><td><code>{token.value}</code></td><td>{token.role}<small>{token.source}</small></td></tr>)}</tbody></table></div></div>)}</details>
      </Section>

      <Section id="actions" className="ds-catalog-actions"><div className="ds-chapter"><span>02 / ACTIONS</span><SectionHeading align="left" accent={tr('действия','actions')}>{tr('Понятные','Clear')}</SectionHeading><p>{tr('Коралловая кнопка ведёт к главному действию. Графитовая поддерживает его. Объём сохраняется при наведении и нажатии.','Coral leads to the primary action. Graphite supports it. Depth remains visible on hover and press.')}</p></div>
        <Spec locale={locale} title={tr('Основная и вторичная','Primary and secondary')} description={tr('Кнопка запускает действие; ссылка ведёт на маршрут. Подписи одной группы согласованы по размеру.','A button starts an action; a link navigates. Labels in one group share the same scale.')} rule={tr('Цель ≥44 px · обычная высота 60 px · большая до 84 px','Target ≥44px · regular height 60px · large up to 84px')} code={snippets.action}><div className="ds-action-row"><Action onClick={()=>setDialog(true)} loading={actionState==='loading'} disabled={actionState==='disabled'}>{tr('Записаться','Book now')}</Action><Action variant="secondary" href="#responsive">{tr('Выбрать доску','Choose a board')}</Action><IconControl label={tr('Следующий вариант','Next option')} direction="next" onClick={()=>setDialog(true)} /></div><div className="ds-demo-selector" role="group" aria-label={tr('Состояние живой кнопки','Live action state')}>{[['ready','Готова','Ready'],['loading','Загрузка','Loading'],['disabled','Недоступна','Disabled']].map(([state,r,e])=><Filter key={state} selected={actionState===state} onClick={()=>setActionState(state)}>{tr(r,e)}</Filter>)}</div></Spec>
        <div className="ds-state-grid">{[['normal','Обычная','Normal'],['hover','Наведение','Hover'],['pressed','Нажатие','Pressed'],['focus','Фокус','Focus'],['disabled','Недоступна','Disabled'],['loading','Загрузка','Loading']].map(([state,r,e])=><div key={state}><p>{tr(r,e)}</p><div inert>{['primary','secondary'].map(variant=><Action key={variant} variant={variant} data-preview-state={state} disabled={state==='disabled'} loading={state==='loading'}>{variant==='primary'?tr('Записаться','Book now'):tr('Выбрать доску','Choose a board')}</Action>)}</div></div>)}</div>
        <div className="ds-size-row"><Action size="small" onClick={()=>setDialog(true)}>{tr('Компактная','Small')}</Action><Action onClick={()=>setDialog(true)}>{tr('Обычная','Regular')}</Action><Action size="large" onClick={()=>setDialog(true)}>{tr('Большая','Large')}</Action><IconControl label={tr('Недоступная стрелка','Disabled arrow')} direction="next" disabled /></div>
      </Section>

      <Section id="surfaces"><div className="ds-chapter"><span>03 / SURFACES</span><SectionHeading align="left" accent={tr('смыслом','purpose')}>{tr('Форма со','Shape with')}</SectionHeading><p>{tr('Информационная карточка, фотография и управляющий элемент имеют разные формы и тени.','Information cards, photos and controls use distinct shapes and shadows.')}</p></div><div className="ds-surface-grid"><Surface tone="dark"><h3>{tr('Графит','Graphite')}</h3><p>{tr('Спокойная поверхность для содержания. Без автоматического hover.','A calm information surface. No automatic button hover.')}</p></Surface><Surface tone="sea"><h3>{tr('Морская панель','Sea panel')}</h3><p>{tr('Связывает пояснение, фотографию и действие в одной композиции.','Connects copy, photography and action in one composition.')}</p></Surface><Surface tone="paper"><h3>{tr('Светлая карточка','Paper card')}</h3><p>{tr('Отзыв или самостоятельный информационный блок.','A review or an independent information block.')}</p></Surface></div>
        <Spec locale={locale} title={tr('Фотография с кадрированием','Framed photography')} description={tr('Рамка сохраняет форму, а фотография внутри использует своё положение и масштаб. Настройки главной доступны по slot.','The frame keeps its shape while the photo uses its own crop and scale. Homepage framing is available by slot.')} rule="cover · desktop/mobile framing · alt" code={snippets.photo}><div className="ds-photo-spec-grid"><FramedPhoto src={`${photoRoot}/meet-photo.webp`} alt={t.howSteps[0].title} slot="how-1" /><FramedPhoto src={`${photoRoot}/theory-photo.webp`} alt={t.howSteps[1].title} slot="how-2" shape="service" /></div></Spec>
      </Section>

      <Section id="compositions"><div className="ds-chapter"><span>04 / COMPOSITIONS</span><SectionHeading align="left" accent={tr('секции','sections')}>{tr('Готовые','Working')}</SectionHeading><p>{tr('Содержание меняется, визуальные решения уже собраны. У каждой композиции есть свои пропорции и границы применения.','Content changes; visual decisions are already assembled. Each composition has its own proportions and scope.')}</p></div>
        <Spec locale={locale} title={tr('Процесс: фото + пояснение','Process: photo + explanation')} description={tr('Два столбца на широком экране, один на узком. Подпись связана с фотографией.','Two columns on wide screens, one on narrow screens. The label belongs to its photo.')} rule={tr('Фото не заменяется декором; текст определяет высоту','Photos remain real; copy can grow the card')} code={snippets.process}><Steps locale={locale} /></Spec>
        <Spec locale={locale} className="ds-textured" title={tr('Услуга, цена и фотография','Service, price and photograph')} description={tr('Пять форматов рядом с фотографией: цены и пояснения видны сразу, стрелки привязаны к фото. Запись здесь демонстрационная.','Five formats beside the photograph: prices and descriptions stay visible, and arrows belong to the image. Booking here is a demonstration.')} code={snippets.service}><LessonDemo locale={locale} onAction={()=>setDialog(true)} /></Spec>
        <Spec locale={locale} title={tr('Что включено','Included')} description={tr('Снаряжение и короткие полезные пояснения. Композиция перестраивается на телефоне.','Gear and short, useful explanations. The composition reflows on phones.')} code={snippets.included}><IncludedDemo locale={locale} /></Spec>
        <Spec locale={locale} title={tr('Проверенный отзыв','Verified review')} description={tr('Четыре строки, настоящее имя и фото автора, ссылка на полный отзыв. Арка без тени кнопки.','Four lines, the real author and portrait, and a full-review link. The arch does not use a button shadow.')} rule={tr('Montserrat 500 · 18 px desktop / 15 px phone · цель ссылки 44 px','Montserrat 500 · 18px desktop / 15px phone · 44px link target')} code={snippets.review}><div className="ds-single-review"><ReviewCard review={googleFeaturedReviews[0]} locale={locale} /></div></Spec>
        <Spec locale={locale} title={tr('Альбом и просмотр фото','Album and photo viewer')} description={tr('Фильтры переключают подборку. Фото открывается в диалоге: Escape, возврат фокуса, стрелки и свайп.','Filters switch albums. Photos open in a dialog with Escape, focus return, arrows and swipe.')} code={snippets.gallery}><GalleryDemo locale={locale} /></Spec>
      </Section>
      <ReviewsSection title={tr('Отзывы учеников','Student reviews')} reviews={googleFeaturedReviews} rating={googleReviewsSummary.rating} href={googleReviewsSummary.referenceUrl} locale={locale} transition />

      <Section id="interaction" tone="paper"><div className="ds-chapter"><span>05 / INTERACTION</span><SectionHeading align="left" recipe="utility">{tr('Ответы, формы и диалоги','Answers, forms and dialogs')}</SectionHeading><p>{tr('Ответ следует содержанию, поле связано с подписью, ошибка объясняет следующий шаг.','Answers follow content, fields have associated labels, and errors explain the next step.')}</p></div><Spec locale={locale} title="FAQ" description={tr('Открывается один ответ. Управление доступно с клавиатуры.','One answer opens at a time. Keyboard controls are available.')} code={snippets.faq}><FAQList items={t.faqItems} /></Spec></Section>
      <Section><Spec locale={locale} title={tr('Форма: обычное, ошибка, загрузка, успех','Form: ready, error, loading, success')} description={tr('Роль поля добавлена для будущих страниц. Образец проверяет только заполнение; данные никуда не отправляются.','Fields are provided for future pages. This sample validates input locally; it does not submit data.')} code={snippets.form}><form className="ds-sample-form" onSubmit={submit} noValidate><Field label={tr('Email','Email')} name="email" type="email" autoComplete="email" required disabled={!ready} value={email} onChange={event=>{setEmail(event.target.value);setFormState('idle');}} help={tr('Введите адрес для проверки состояния формы.','Enter an address to try the form states.')} error={submitted&&!validEmail?tr('Введите email в формате name@example.com.','Use an email such as name@example.com.'):undefined} /><Field as="textarea" label={tr('Комментарий','Comment')} name="message" rows={3} disabled={!ready} placeholder={tr('Длинный текст свободно переносится.','Long text wraps naturally.')} /><Field label={tr('Недоступное поле','Disabled field')} disabled defaultValue={tr('Пример недоступного значения','An unavailable value')} /><div className="ds-action-row"><Action type="submit" disabled={!ready} loading={formState==='loading'}>{tr('Проверить форму','Try form')}</Action><Action variant="secondary" onClick={()=>setDialog(true)}>{tr('Открыть диалог','Open dialog')}</Action></div>{formState==='error'&&<FormStatus kind="error">{tr('Проверьте email перед продолжением.','Check your email before continuing.')}</FormStatus>}{formState==='success'&&<FormStatus kind="success">{tr('Пример заполнен правильно. Данные не отправлялись.','The sample is valid. No data was submitted.')}</FormStatus>}</form></Spec></Section>

      <Section id="responsive"><div className="ds-chapter"><span>06 / RESPONSIVE</span><SectionHeading align="left" accent={tr('масштаб','scale')}>{tr('Настоящий','Real')}</SectionHeading><p>{tr('Ширина iframe — ширина браузера образца. Проверяйте композицию и переносы; на узком экране широкий образец прокручивается внутри рамки.','The iframe width is the sample viewport width. Check layouts and wrapping; wide samples scroll within the frame on narrow screens.')}</p></div><div className="ds-demo-selector" role="group" aria-label={tr('Ширина образца','Sample width')}>{['390','1024','1440','2560','fluid'].map(width=><Filter key={width} selected={previewWidth===width} onClick={()=>setPreviewWidth(width)}>{width==='fluid'?tr('По ширине окна','Fit window'):`${width} px`}</Filter>)}</div><div className="ds-preview-interaction"><Filter selected={previewActive} onClick={()=>setPreviewActive(!previewActive)}>{previewActive?tr('Выключить взаимодействие','Disable interaction'):tr('Включить взаимодействие','Enable interaction')}</Filter><p>{tr('Включите, чтобы прокручивать образец и нажимать его кнопки.','Enable to scroll the sample and use its controls.')}</p></div><div className="ds-responsive-shell"><iframe inert={!previewActive} tabIndex={previewActive?0:-1} key={`${locale}-${previewWidth}`} title={tr('Адаптивные образцы дизайн-системы','Responsive design-system samples')} src={`/design-system?preview=1&lang=${locale}`} loading="lazy" className="ds-responsive-frame" style={{width:previewWidth==='fluid'?'100%':`${previewWidth}px`,pointerEvents:previewActive?'auto':'none'}} /></div><p className="ds-preview-note">{tr('Границы: mobile <700 · процесс 1000 · desktop ≥1200. Максимальная композиция — 2160 px.','Breakpoints: mobile <700 · process 1000 · desktop ≥1200. The composition caps at 2160px.')}</p></Section>

      <Section id="usage"><div className="ds-chapter"><span>07 / BUILD</span><SectionHeading align="left" accent={tr('страницы','pages')}>{tr('Собирать','Build new')}</SectionHeading><p>{tr('Выберите задачу → каркас → секции → содержание EN/RU → фото → проверка. Компоненты находятся в app/components/design-system.','Choose the task → frame → sections → EN/RU content → photos → validation. Components live in app/components/design-system.')}</p></div><CodeExample locale={locale} code={snippets.frame} /><div className="ds-intro-actions"><Action href={locale==='ru'?'/ru/surf-lessons-danang':'/surf-lessons-danang'}>{tr('Посмотреть страницу уроков','View the lesson page')}</Action></div><div className="ds-usage-grid"><Surface><h3>{tr('Одна библиотека','One library')}</h3><p>{tr('Каталог использует те же exports, которые импортируются на новые страницы. Оформление меняется через общие роли.','The catalog uses the same exports as new pages. Appearance changes through shared roles.')}</p></Surface><Surface><h3>{tr('Свои обработчики','Your handlers')}</h3><p>{tr('Booking, rental, tracking и partner attribution остаются у страницы. Библиотека принимает href и callbacks.','Booking, rental, tracking and partner attribution stay with the page. The library accepts hrefs and callbacks.')}</p></Surface><Surface><h3>{tr('Первый шаблон страницы','First page template')}</h3><p>{tr('Страница уроков пересобрана по выбранному фото-макету. Новый выбор формата и актуальный коллаж Included доступны здесь же; остальные страницы переносим после проверки пилота.','The lesson page follows the selected photo-led mockup. Its format chooser and current Included artwork are reusable here; further page migrations follow pilot review.')}</p></Surface></div></Section>
    </main><footer className="ds-catalog-footer"><ContentFrame><span>EPIC SURF SCHOOL / DESIGN SYSTEM V1</span><a href="#top">{tr('Наверх','Back to top')} ↑</a></ContentFrame></footer>
    <Dialog open={dialog} onClose={()=>setDialog(false)} title={tr('Пример диалога','Dialog example')} closeLabel={tr('Закрыть диалог','Close dialog')}><p>{tr('Такая оболочка сохраняет фокус и блокирует прокрутку фона. Внутрь можно передать форму записи или аренды.','This shell contains focus and locks background scrolling. It can wrap booking or rental content.')}</p><Field label={tr('Ваше имя','Your name')} name="example-name" placeholder={tr('Имя','Name')} /><Action onClick={()=>setDialog(false)}>{tr('Готово','Done')}</Action></Dialog>
  </PageFrame>;
}
