// This registry supplies both runtime CSS variables and the catalog reference.
// Component recipes may alias these values; do not copy them into page CSS.
const foundation = 'docs/design/foundations.md';
const layout = 'docs/design/layout-and-scale.md';
const make = (name, value, role, source = foundation) => ({ name: `--ds-${name}`, value, role, source });
export const tokenGroups = [
  { id: 'color', label: 'Color / Цвет', tokens: [
    make('coral', '#FE746A', 'Primary action / Основное действие'),
    make('graphite', '#2E2E2E', 'Dark surface / Тёмная поверхность'),
    make('deep', '#1F1F1F', 'Hero and process / Hero и процесс'),
    make('paper', '#F6F6F6', 'Paper and light text / Светлая поверхность и текст'),
    make('teal', '#395962', 'Deep sea / Глубокий морской'),
    make('sea', '#598D80', 'Sea surface / Морская поверхность'),
    make('mint', '#AAFFC7', 'Small accent / Редкий акцент'),
    make('ink', '#353535', 'Text on paper / Текст на светлом'),
    make('action-ink', '#292929', 'Text on coral / Текст на коралловом'),
    make('muted-light', '#DDD', 'Secondary on dark / Вторичный на тёмном'),
    make('muted-dark', '#666', 'Secondary on paper / Вторичный на светлом'),
  ] },
  { id: 'surface', label: 'Surface / Поверхности', tokens: [
    make('fill-coral', 'linear-gradient(165deg, #ff8d80 0%, #fe746a 55%, #ee665e 100%)', 'Primary CTA'),
    make('fill-graphite', 'linear-gradient(165deg, #858585 0%, #686868 55%, #505050 100%)', 'Secondary CTA desktop'),
    make('fill-sea', 'linear-gradient(155deg, #70a99b 0%, #598d80 55%, #477568 100%)', 'Round sea control'),
    make('fill-panel', 'linear-gradient(150deg, #659e90, #598d80 60%, #4d7d70)', 'Description panel'),
    make('fill-process', 'linear-gradient(145deg, #1c1c1c, #171717)', 'Process card'),
    make('fill-sunset', 'linear-gradient(155deg, #4c7c73 10%, #749988 58%, #e4ae86 100%)', 'Static section transition'),
    make('coral-edge', '#4A302C', 'Primary border and lower edge'),
    make('graphite-edge', '#202020', 'Secondary lower edge'),
    make('graphite-mobile', '#6C6C6C', 'Secondary CTA phone'),
    make('graphite-mobile-edge', '#494949', 'Secondary lower edge phone'),
  ] },
  { id: 'type', label: 'Typography / Типографика', tokens: [
    make('font-display-en', '"Home V5 Recursive", monospace', 'Expressive EN heading'),
    make('font-display-ru', '"Home V5 Recursive", Consolas, monospace', 'Current RU heading fallback, DS-01'),
    make('font-service-display', '"EPIC Lesson Display", "Home V5 Recursive", monospace', 'Selected photo-led service heading; local Neucha EN/RU'),
    make('font-body-en', '"Home V2 Lessons Chivo", Arial, sans-serif', 'EN body'),
    make('font-body-ru', 'Arial, sans-serif', 'Explicit RU body fallback, DS-01'),
    make('font-label', '"Home V2 Lessons Montserrat", Arial, sans-serif', 'Labels, prices and CTA; EN/RU'),
    make('font-utility', '"Segoe UI", Arial, sans-serif', 'FAQ and fields'),
    make('body-size', 'clamp(16px, 1.2vw, 20px)', 'Ordinary body, bounded'),
    make('heading-size', 'clamp(32px, calc(var(--ds-content-unit) * 2.666667), 44px)', 'Desktop heading', layout),
    make('hero-size', 'clamp(36px, 4.8vw, 68px)', 'Compact text-led hero heading', layout),
    make('photo-hero-size', 'clamp(80px, 6.6vw, 104px)', 'Selected photo-led service hero, desktop', layout),
    make('heading-mobile', 'clamp(24px, 6.2vw, 32px)', 'Phone heading'),
    make('label-size', 'clamp(16px, calc(var(--ds-stage-unit) * 1.4), 22px)', 'Large CTA label', layout),
    make('body-leading', '1.5', 'Ordinary body leading'),
    make('readable', '68ch', 'Readable column inside shared frame', layout),
  ] },
  { id: 'layout', label: 'Layout / Геометрия', tokens: [
    make('stage-desktop', 'min(94vw, 2160px)', 'Bounded composition, >=1200px', layout),
    make('content-share', '.832', 'Content as a share of stage', layout),
    make('page-gutter', 'clamp(18px, 4vw, 48px)', 'Mobile/tablet outer gutter'),
    make('section-space', 'clamp(64px, 5vw, 96px)', 'Ordinary section spacing', layout),
    make('heading-gap', '32px', 'Heading to section content', layout),
    make('grid-gap', '24px', 'Standard content gap'),
    make('card-padding', '24px 30px', 'Review information surface'),
    make('control-min', '44px', 'Minimum target size for new controls', layout),
    make('action-height', '60px', 'Regular CTA height'),
    make('action-large', 'clamp(60px, calc(var(--ds-stage-unit) * 4.785), 84px)', 'Large CTA, bounded', layout),
    make('decor-clearance', '144px', 'Review to visible wave clearance', layout),
  ] },
  { id: 'shape', label: 'Shape / Скругления', tokens: [
    make('radius-card', '40px', 'Review/paper card'),
    make('radius-process', '44px', 'Phone process card'),
    make('radius-photo', '48px', 'Process photograph'),
    make('radius-service', '70px', 'Phone service photograph'),
    make('radius-gallery', '32px', 'Phone gallery tile'),
    make('radius-dialog', '40px', 'Dialog shell'),
    make('radius-field', '18px', 'New field role derived from utility/dialog surfaces'),
    make('radius-pill', '999px', 'CTA/filter capsule'),
  ] },
  { id: 'depth', label: 'Depth / Объём', tokens: [
    make('shadow-card', 'inset 0 1px 0 rgb(255 255 255 / 12%), 0 5px 0 rgb(0 0 0 / 14%), 0 18px 28px -12px rgb(0 0 0 / 30%)', 'Information surface'),
    make('shadow-coral', 'inset 0 2px 1px rgb(255 255 255 / 30%), 0 5px 0 var(--ds-coral-edge), 0 14px 22px -8px rgb(0 0 0 / 38%)', 'Primary normal'),
    make('shadow-coral-hover', 'inset 0 2px 1px rgb(255 255 255 / 35%), 0 8px 0 var(--ds-coral-edge), 0 18px 26px -8px rgb(0 0 0 / 38%)', 'Primary hover'),
    make('shadow-coral-pressed', 'inset 0 1px 3px rgb(0 0 0 / 12%), 0 1px 0 var(--ds-coral-edge), 0 5px 9px -4px rgb(0 0 0 / 24%)', 'Primary pressed'),
    make('shadow-secondary', 'inset 0 2px 1px rgb(255 255 255 / 30%), 0 5px 0 var(--ds-graphite-edge), 0 14px 22px -8px rgb(0 0 0 / 38%)', 'Secondary normal'),
    make('shadow-secondary-hover', 'inset 0 2px 1px rgb(255 255 255 / 35%), 0 8px 0 var(--ds-graphite-edge), 0 18px 26px -8px rgb(0 0 0 / 38%)', 'Secondary hover'),
    make('shadow-secondary-pressed', 'inset 0 1px 3px rgb(0 0 0 / 12%), 0 1px 0 var(--ds-graphite-edge), 0 5px 9px -4px rgb(0 0 0 / 24%)', 'Secondary pressed'),
    make('shadow-secondary-mobile', 'inset 0 2px 1px rgb(255 255 255 / 30%), 0 5px 0 var(--ds-graphite-mobile-edge), 0 14px 22px -8px rgb(0 0 0 / 38%)', 'Secondary phone normal'),
    make('shadow-secondary-mobile-hover', 'inset 0 2px 1px rgb(255 255 255 / 35%), 0 8px 0 var(--ds-graphite-mobile-edge), 0 18px 26px -8px rgb(0 0 0 / 38%)', 'Secondary phone hover'),
    make('shadow-secondary-mobile-pressed', 'inset 0 1px 3px rgb(0 0 0 / 12%), 0 1px 0 var(--ds-graphite-mobile-edge), 0 5px 9px -4px rgb(0 0 0 / 24%)', 'Secondary phone pressed'),
    make('shadow-raised', 'inset 0 2px 1px rgb(255 255 255 / 18%), 0 4px 0 rgb(0 0 0 / 24%), 0 12px 20px -8px rgb(0 0 0 / 32%)', 'Compact control'),
    make('shadow-photo', '0 0 0 1px rgb(255 255 255 / 12%), 0 10px 20px -10px rgb(0 0 0 / 30%)', 'Photo frame'),
    make('shadow-dialog', '0 24px 100px rgb(0 0 0 / 40%)', 'Dialog/lightbox shell'),
  ] },
  { id: 'motion', label: 'Motion / Движение', tokens: [
    make('feedback', '160ms ease', 'Action feedback'),
    make('hover-shift', '-3px', 'Large CTA lift'),
    make('pressed-shift', '4px', 'Large CTA press'),
    make('focus-width', '3px', 'Visible focus ring'),
    make('focus-offset', '7px', 'Large CTA ring clearance'),
  ] },
];
export const tokenVariables = Object.fromEntries(tokenGroups.flatMap(group => group.tokens.map(token => [token.name, token.value])));
